trigger:
  branches:
    include: [master]

pool:
  vmImage: ubuntu-latest

variables:
  - group: loa-dev
  - name: buildConfiguration
    value: Release
  - name: dotnetversion
    value: '10.0.x'

stages:
  - stage: Build
    jobs:
      - job: BuildAndTest
        steps:
          - task: UseDotNet@2
            inputs:
              version: $(dotnetversion)
              includePreviewVersions: false

          - script: dotnet restore LoaTracker.sln
            displayName: Restore

          - script: dotnet build LoaTracker.sln -c $(buildConfiguration) --no-restore
            displayName: Build
          
          # Publish API
          # - script: |
          #     dotnet publish LoaTracker.ApiService/LoaTracker.ApiService.csproj \
          #       -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/api
          #   displayName: Publish Api

          - task: DotNetCoreCLI@2
            displayName: Publish Api to Web App
            inputs:
              command: publish
              publishWebProjects: false
              projects: LoaTracker.ApiService/LoaTracker.ApiService.csproj
              arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api
              zipAfterPublish: true
              modifyOutputPath: false

          # Publish Fuction
          - task: DotNetCoreCLI@2
            displayName: Publish Function
            inputs:
              command: publish
              publishWebProjects: false
              projects: LoaTracker.Functions/LoaTracker_Functions.csproj
              arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/functions
              zipAfterPublish: true
              modifyOutputPath: false
          
          - publish: $(Build.ArtifactStagingDirectory)
            artifact: drop
  
  - stage: Deploy_Dev
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployToDev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - script: |
                    echo "=== Staging directory ==="
                    ls -la $(Build.ArtifactStagingDirectory)
                    ls -la $(Pipeline.Workspace)/drop/api
                    echo "=============="
                    find $(Build.SourcesDirectory) -name "*.zip" -o -name "publish" -type d
                  displayName: Debug - check 

                - task: AzureWebApp@1
                  displayName: Deploy API
                  inputs:
                    azureSubscription: 'sc-loa-azure-dev'  # service connection name
                    appType: webAppLinux
                    appName: app-loa-api-dev
                    package: $(Pipeline.Workspace)/drop/api/api.zip
                    deploymentMethod: zipDeploy

                - task: AzureFunctionApp@2
                  displayName: Deploy to Function
                  inputs:
                    azureSubscription: 'sc-loa-azure-dev'
                    appType: functionAppLinux
                    appName: func-loa-dev
                    package: $(Pipeline.Workspace)/drop/functions/functions.zip
                    deploymentMethod: zipDeploy
                    runtimeStack: 'DOTNET-ISOLATED|10'

